swagger: '2.0'
info:
  title: artchive-api-config
  description: API config for artchive-api
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /api:
    get:
      summary: artchive api functions
      operationId: api
      x-google-backend:
        address: https://us-central1-artchive.cloudfunctions.net/api
      responses:
        '200':
          description: A successful response
          schema:
            type: string
